version: '3'

services:

  testphp-cli:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

