App\Steps\IncrementStep: &IncrementStep
  class: App\Steps\IncrementStep
  dependencies: []

App\Steps\DecrementStep: &DecrementStep
  class: App\Steps\DecrementStep
  dependencies: []

App\Steps\NotProcessedStep: &NotProcessedStep
  class: App\Steps\NotProcessedStep
  dependencies: []

App\Steps\NotProcessedStep: &BrokenStep
  class: App\Steps\BrokenStep
  dependencies: []


calculate_thread: &calculate_thread
  class: App\Thread\CalculationThread
  context: App\Context\CalculationContextComposite
  steps:
    - *IncrementStep
    - *DecrementStep
    - *IncrementStep
    - *NotProcessedStep
    - *IncrementStep
    - *NotProcessedStep
    - *BrokenStep
    - *IncrementStep
    - *IncrementStep



App\Steps\BusinessLogicMaximumStep: &BusinessLogicMaximumStep
  class: App\Steps\BusinessLogicMaximumStep
  dependencies: []

App\Steps\BusinessLogicMinimumStep: &BusinessLogicMinimumStep
  class: App\Steps\BusinessLogicMinimumStep
  dependencies: []


business_logic_thread: &business_logic_thread
  class: App\Thread\BusinessLogicThread
  context: App\Context\CalculationContextComposite
  steps:
    - *BusinessLogicMaximumStep
    - *BusinessLogicMinimumStep


calculate_with_business_logic_thread: &calculate_with_business_logic_thread
  class: App\Thread\CalculationThread
  context: App\Context\CalculationContextComposite
  steps:
    - *calculate_thread
    - *IncrementStep
    - *IncrementStep
    - *NotProcessedStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *DecrementStep
    - *business_logic_thread


max_calculate_with_business_logic_thread: &calculate_with_business_logic_thread
  class: App\Thread\CalculationThread
  context: App\Context\CalculationContextComposite
  steps:
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *IncrementStep
    - *business_logic_thread

min_calculate_with_business_logic_thread: &calculate_with_business_logic_thread
  class: App\Thread\CalculationThread
  context: App\Context\CalculationContextComposite
  steps:
    - *DecrementStep
    - *DecrementStep
    - *DecrementStep
    - *business_logic_thread
